package constants

const (
	ROUTER_ADDRESS = "127.0.0.1"
	INTERFACE_PORT = 5002
)

const (
	SENSOR_WEBSOCKET_PATH = "/sensors"
	SENSOR_WEBSOCKET_PORT = 5001
	SENSOR_WEBSOCKET_NAME = "SENSORS_SETTINGS"
)

const (
	OUTPUT_WEBSOCKET_PATH = "/output"
	OUTPUT_WEBSOCKET_PORT = 5003
	OUTPUT_WEBSOCKET_NAME = "OUTPUT_FSHK"
)

const (
	UDP_ADDR            = "127.0.0.1"
	UDP_PORT            = 5010
	MAX_UDP_PACKET_SIZE = 1000
)

const (
	TCP_ADDR            = "127.0.0.1"
	TCP_PORT            = 5020
	MAX_TCP_PACKET_SIZE = 1000
)

const (
	ZWAVE_ADDR       = "127.0.0.1"
	ZWAVE_INPUT_PORT = "/dev/ttyACM0"
	ZWAVE_PORT       = 5030
)

const (
	WEBSOCKET_INNER_BLE_ADDR = ""
	WEBSOCKET_INNER_BLE_PATH = "/ble"
	WEBSOCKET_INNER_BLE_NAME = "BLE_INPUT"
	WEBSOCKET_INNER_BLE_PORT = 5030
)

const (
	MESSAGING_DATATYPE_CHECKUP = 0x10
	MESSAGING_DATATYPE_AUTH    = 0x01
	MESSAGING_DATATYPE_DATA    = 0x00
)

const PROTOCOLS_JSON_CONF = "protocols.json"
